// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: linker/object.proto

package linker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnaryType int32

const (
	UnaryType_ADD      UnaryType = 0
	UnaryType_SUBTRACT UnaryType = 1
)

// Enum value maps for UnaryType.
var (
	UnaryType_name = map[int32]string{
		0: "ADD",
		1: "SUBTRACT",
	}
	UnaryType_value = map[string]int32{
		"ADD":      0,
		"SUBTRACT": 1,
	}
)

func (x UnaryType) Enum() *UnaryType {
	p := new(UnaryType)
	*p = x
	return p
}

func (x UnaryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnaryType) Descriptor() protoreflect.EnumDescriptor {
	return file_linker_object_proto_enumTypes[0].Descriptor()
}

func (UnaryType) Type() protoreflect.EnumType {
	return &file_linker_object_proto_enumTypes[0]
}

func (x UnaryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnaryType.Descriptor instead.
func (UnaryType) EnumDescriptor() ([]byte, []int) {
	return file_linker_object_proto_rawDescGZIP(), []int{0}
}

type SymbolSize int32

const (
	SymbolSize_WORD     SymbolSize = 0
	SymbolSize_BYTE     SymbolSize = 1
	SymbolSize_RELATIVE SymbolSize = 2
)

// Enum value maps for SymbolSize.
var (
	SymbolSize_name = map[int32]string{
		0: "WORD",
		1: "BYTE",
		2: "RELATIVE",
	}
	SymbolSize_value = map[string]int32{
		"WORD":     0,
		"BYTE":     1,
		"RELATIVE": 2,
	}
)

func (x SymbolSize) Enum() *SymbolSize {
	p := new(SymbolSize)
	*p = x
	return p
}

func (x SymbolSize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SymbolSize) Descriptor() protoreflect.EnumDescriptor {
	return file_linker_object_proto_enumTypes[1].Descriptor()
}

func (SymbolSize) Type() protoreflect.EnumType {
	return &file_linker_object_proto_enumTypes[1]
}

func (x SymbolSize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SymbolSize.Descriptor instead.
func (SymbolSize) EnumDescriptor() ([]byte, []int) {
	return file_linker_object_proto_rawDescGZIP(), []int{1}
}

type Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fragments map[string]*Fragment `protobuf:"bytes,1,rep,name=fragments,proto3" json:"fragments,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Object) Reset() {
	*x = Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linker_object_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_linker_object_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_linker_object_proto_rawDescGZIP(), []int{0}
}

func (x *Object) GetFragments() map[string]*Fragment {
	if x != nil {
		return x.Fragments
	}
	return nil
}

type Fragment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expressions []*Expression `protobuf:"bytes,1,rep,name=expressions,proto3" json:"expressions,omitempty"`
}

func (x *Fragment) Reset() {
	*x = Fragment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linker_object_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fragment) ProtoMessage() {}

func (x *Fragment) ProtoReflect() protoreflect.Message {
	mi := &file_linker_object_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fragment.ProtoReflect.Descriptor instead.
func (*Fragment) Descriptor() ([]byte, []int) {
	return file_linker_object_proto_rawDescGZIP(), []int{1}
}

func (x *Fragment) GetExpressions() []*Expression {
	if x != nil {
		return x.Expressions
	}
	return nil
}

type Expression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Inner:
	//
	//	*Expression_Literal_
	//	*Expression_Symbol_
	//	*Expression_Unary_
	//	*Expression_Subsymbol_
	Inner isExpression_Inner `protobuf_oneof:"inner"`
}

func (x *Expression) Reset() {
	*x = Expression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linker_object_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_linker_object_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_linker_object_proto_rawDescGZIP(), []int{2}
}

func (m *Expression) GetInner() isExpression_Inner {
	if m != nil {
		return m.Inner
	}
	return nil
}

func (x *Expression) GetLiteral() *Expression_Literal {
	if x, ok := x.GetInner().(*Expression_Literal_); ok {
		return x.Literal
	}
	return nil
}

func (x *Expression) GetSymbol() *Expression_Symbol {
	if x, ok := x.GetInner().(*Expression_Symbol_); ok {
		return x.Symbol
	}
	return nil
}

func (x *Expression) GetUnary() *Expression_Unary {
	if x, ok := x.GetInner().(*Expression_Unary_); ok {
		return x.Unary
	}
	return nil
}

func (x *Expression) GetSubsymbol() *Expression_Subsymbol {
	if x, ok := x.GetInner().(*Expression_Subsymbol_); ok {
		return x.Subsymbol
	}
	return nil
}

type isExpression_Inner interface {
	isExpression_Inner()
}

type Expression_Literal_ struct {
	Literal *Expression_Literal `protobuf:"bytes,1,opt,name=literal,proto3,oneof"`
}

type Expression_Symbol_ struct {
	Symbol *Expression_Symbol `protobuf:"bytes,2,opt,name=symbol,proto3,oneof"`
}

type Expression_Unary_ struct {
	Unary *Expression_Unary `protobuf:"bytes,3,opt,name=unary,proto3,oneof"`
}

type Expression_Subsymbol_ struct {
	Subsymbol *Expression_Subsymbol `protobuf:"bytes,4,opt,name=subsymbol,proto3,oneof"`
}

func (*Expression_Literal_) isExpression_Inner() {}

func (*Expression_Symbol_) isExpression_Inner() {}

func (*Expression_Unary_) isExpression_Inner() {}

func (*Expression_Subsymbol_) isExpression_Inner() {}

type Expression_Literal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Expression_Literal) Reset() {
	*x = Expression_Literal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linker_object_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expression_Literal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression_Literal) ProtoMessage() {}

func (x *Expression_Literal) ProtoReflect() protoreflect.Message {
	mi := &file_linker_object_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression_Literal.ProtoReflect.Descriptor instead.
func (*Expression_Literal) Descriptor() ([]byte, []int) {
	return file_linker_object_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Expression_Literal) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Expression_Symbol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size SymbolSize `protobuf:"varint,2,opt,name=size,proto3,enum=SymbolSize" json:"size,omitempty"`
}

func (x *Expression_Symbol) Reset() {
	*x = Expression_Symbol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linker_object_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expression_Symbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression_Symbol) ProtoMessage() {}

func (x *Expression_Symbol) ProtoReflect() protoreflect.Message {
	mi := &file_linker_object_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression_Symbol.ProtoReflect.Descriptor instead.
func (*Expression_Symbol) Descriptor() ([]byte, []int) {
	return file_linker_object_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Expression_Symbol) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Expression_Symbol) GetSize() SymbolSize {
	if x != nil {
		return x.Size
	}
	return SymbolSize_WORD
}

type Expression_Subsymbol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Expression_Subsymbol) Reset() {
	*x = Expression_Subsymbol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linker_object_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expression_Subsymbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression_Subsymbol) ProtoMessage() {}

func (x *Expression_Subsymbol) ProtoReflect() protoreflect.Message {
	mi := &file_linker_object_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression_Subsymbol.ProtoReflect.Descriptor instead.
func (*Expression_Subsymbol) Descriptor() ([]byte, []int) {
	return file_linker_object_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Expression_Subsymbol) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Expression_Unary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind  UnaryType   `protobuf:"varint,1,opt,name=kind,proto3,enum=UnaryType" json:"kind,omitempty"`
	Value *Expression `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Expression_Unary) Reset() {
	*x = Expression_Unary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linker_object_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expression_Unary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression_Unary) ProtoMessage() {}

func (x *Expression_Unary) ProtoReflect() protoreflect.Message {
	mi := &file_linker_object_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression_Unary.ProtoReflect.Descriptor instead.
func (*Expression_Unary) Descriptor() ([]byte, []int) {
	return file_linker_object_proto_rawDescGZIP(), []int{2, 3}
}

func (x *Expression_Unary) GetKind() UnaryType {
	if x != nil {
		return x.Kind
	}
	return UnaryType_ADD
}

func (x *Expression_Unary) GetValue() *Expression {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_linker_object_proto protoreflect.FileDescriptor

var file_linker_object_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x34, 0x0a, 0x09, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x46, 0x72, 0x61,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x66, 0x72, 0x61,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x47, 0x0a, 0x0e, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x46, 0x72, 0x61, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x39, 0x0a, 0x08, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x0b, 0x65,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x65,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xa3, 0x03, 0x0a, 0x0a, 0x45,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x07, 0x6c, 0x69, 0x74,
	0x65, 0x72, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x45, 0x78, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x48,
	0x00, 0x52, 0x07, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x45, 0x78, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x48, 0x00,
	0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x29, 0x0a, 0x05, 0x75, 0x6e, 0x61, 0x72,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x48, 0x00, 0x52, 0x05, 0x75, 0x6e,
	0x61, 0x72, 0x79, 0x12, 0x35, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x48, 0x00, 0x52,
	0x09, 0x73, 0x75, 0x62, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x1a, 0x1f, 0x0a, 0x07, 0x4c, 0x69,
	0x74, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x3d, 0x0a, 0x06, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x53, 0x69, 0x7a, 0x65, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x1a, 0x1f, 0x0a, 0x09, 0x53, 0x75,
	0x62, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x4a, 0x0a, 0x05, 0x55,
	0x6e, 0x61, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x12, 0x21, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72,
	0x2a, 0x22, 0x0a, 0x09, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a,
	0x03, 0x41, 0x44, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x55, 0x42, 0x54, 0x52, 0x41,
	0x43, 0x54, 0x10, 0x01, 0x2a, 0x2e, 0x0a, 0x0a, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x42, 0x59, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x4c, 0x41, 0x54, 0x49,
	0x56, 0x45, 0x10, 0x02, 0x42, 0x0d, 0x5a, 0x0b, 0x53, 0x61, 0x6e, 0x6f, 0x2f, 0x6c, 0x69, 0x6e,
	0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_linker_object_proto_rawDescOnce sync.Once
	file_linker_object_proto_rawDescData = file_linker_object_proto_rawDesc
)

func file_linker_object_proto_rawDescGZIP() []byte {
	file_linker_object_proto_rawDescOnce.Do(func() {
		file_linker_object_proto_rawDescData = protoimpl.X.CompressGZIP(file_linker_object_proto_rawDescData)
	})
	return file_linker_object_proto_rawDescData
}

var file_linker_object_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_linker_object_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_linker_object_proto_goTypes = []interface{}{
	(UnaryType)(0),               // 0: UnaryType
	(SymbolSize)(0),              // 1: SymbolSize
	(*Object)(nil),               // 2: Object
	(*Fragment)(nil),             // 3: Fragment
	(*Expression)(nil),           // 4: Expression
	nil,                          // 5: Object.FragmentsEntry
	(*Expression_Literal)(nil),   // 6: Expression.Literal
	(*Expression_Symbol)(nil),    // 7: Expression.Symbol
	(*Expression_Subsymbol)(nil), // 8: Expression.Subsymbol
	(*Expression_Unary)(nil),     // 9: Expression.Unary
}
var file_linker_object_proto_depIdxs = []int32{
	5,  // 0: Object.fragments:type_name -> Object.FragmentsEntry
	4,  // 1: Fragment.expressions:type_name -> Expression
	6,  // 2: Expression.literal:type_name -> Expression.Literal
	7,  // 3: Expression.symbol:type_name -> Expression.Symbol
	9,  // 4: Expression.unary:type_name -> Expression.Unary
	8,  // 5: Expression.subsymbol:type_name -> Expression.Subsymbol
	3,  // 6: Object.FragmentsEntry.value:type_name -> Fragment
	1,  // 7: Expression.Symbol.size:type_name -> SymbolSize
	0,  // 8: Expression.Unary.kind:type_name -> UnaryType
	4,  // 9: Expression.Unary.value:type_name -> Expression
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_linker_object_proto_init() }
func file_linker_object_proto_init() {
	if File_linker_object_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_linker_object_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linker_object_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fragment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linker_object_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linker_object_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expression_Literal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linker_object_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expression_Symbol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linker_object_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expression_Subsymbol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linker_object_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expression_Unary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_linker_object_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Expression_Literal_)(nil),
		(*Expression_Symbol_)(nil),
		(*Expression_Unary_)(nil),
		(*Expression_Subsymbol_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_linker_object_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_linker_object_proto_goTypes,
		DependencyIndexes: file_linker_object_proto_depIdxs,
		EnumInfos:         file_linker_object_proto_enumTypes,
		MessageInfos:      file_linker_object_proto_msgTypes,
	}.Build()
	File_linker_object_proto = out.File
	file_linker_object_proto_rawDesc = nil
	file_linker_object_proto_goTypes = nil
	file_linker_object_proto_depIdxs = nil
}
